server:
  log_level: "debug"

channel:
  host: "localhost"
  port: 1491
  tcp_timeout: 300
  auth_password: "SecretPassword"

channel.search:
  query_limit_default: 10
  query_limit_maximum: 100
  query_alternates_try: 4
  suggest_limit_default: 5
  suggest_limit_maximum: 20
  list_limit_default: 100
  list_limit_maximum: 500

store:
  kv:
    path: "./data/store/kv/"
    retain_word_objects: 1000
    pool:
      inactive_after: 1800
    database:
      flush_after: 900
      compress: true
      parallelism: 2
      max_files: 100
      max_compactions: 1
      max_flushes: 1
      write_buffer: 16384
      write_ahead_log: true

  fst:
    path: "./data/store/fst/"
    pool:
      inactive_after: 300
    graph:
      consolidate_after: 180
      max_size: 2048
      max_words: 250000
